# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grpcs/grpcapi-go-server/article.proto for package 'Grpcs.GrpcapiGoServer.Article'

require 'grpc'
require 'grpcs/grpcapi-go-server/article_pb'

module Grpcs
  module GrpcapiGoServer
    module Article
      module ArticleService
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'article.ArticleService'

          rpc :GetArticle, ::Grpcs::GrpcapiGoServer::Article::GetArticleRequest, ::Grpcs::GrpcapiGoServer::Article::GetArticleResponse
          rpc :ListArticles, ::Grpcs::GrpcapiGoServer::Article::ListArticlesRequest, ::Grpcs::GrpcapiGoServer::Article::ListArticlesResponse
          rpc :CreateArticle, ::Grpcs::GrpcapiGoServer::Article::CreateArticleRequest, ::Grpcs::GrpcapiGoServer::Article::CreateArticleResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
