# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcs/grpcapi-go-server/article.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("grpcs/grpcapi-go-server/article.proto", :syntax => :proto3) do
    add_message "article.GetArticleRequest" do
      optional :id, :uint64, 1
    end
    add_message "article.GetArticleResponse" do
      optional :article, :message, 1, "article.Article"
    end
    add_message "article.ListArticlesRequest" do
    end
    add_message "article.ListArticlesResponse" do
      repeated :articles, :message, 1, "article.Article"
    end
    add_message "article.CreateArticleRequest" do
      optional :title, :string, 1
    end
    add_message "article.CreateArticleResponse" do
      optional :article, :message, 1, "article.Article"
    end
    add_message "article.Article" do
      optional :id, :uint64, 1
      optional :title, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

module Grpcs
  module GrpcapiGoServer
    module Article
      GetArticleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.GetArticleRequest").msgclass
      GetArticleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.GetArticleResponse").msgclass
      ListArticlesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.ListArticlesRequest").msgclass
      ListArticlesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.ListArticlesResponse").msgclass
      CreateArticleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.CreateArticleRequest").msgclass
      CreateArticleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.CreateArticleResponse").msgclass
      Article = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.Article").msgclass
    end
  end
end
