# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("article.proto", :syntax => :proto3) do
    add_message "article.GetRequest" do
      optional :id, :uint64, 1
    end
    add_message "article.GetResponse" do
      optional :article, :message, 1, "article.ArticleResponse"
    end
    add_message "article.ListRequest" do
    end
    add_message "article.ListResponse" do
      repeated :articles, :message, 1, "article.ArticleResponse"
    end
    add_message "article.CreateRequest" do
      optional :title, :string, 1
    end
    add_message "article.CreateResponse" do
      optional :article, :message, 1, "article.ArticleResponse"
    end
    add_message "article.ArticleResponse" do
      optional :id, :uint64, 1
      optional :title, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
      optional :updated_at, :message, 4, "google.protobuf.Timestamp"
    end
  end
end

module Proto
  module Article
    GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.GetRequest").msgclass
    GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.GetResponse").msgclass
    ListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.ListRequest").msgclass
    ListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.ListResponse").msgclass
    CreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.CreateRequest").msgclass
    CreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.CreateResponse").msgclass
    ArticleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("article.ArticleResponse").msgclass
  end
end
