# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: article.proto for package 'Proto.Article'

require 'grpc'
require 'article_pb'

module Proto
  module Article
    module Article
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'article.Article'

        rpc :Get, ::Proto::Article::GetRequest, ::Proto::Article::GetResponse
        rpc :List, ::Proto::Article::ListRequest, ::Proto::Article::ListResponse
        rpc :Create, ::Proto::Article::CreateRequest, ::Proto::Article::CreateResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
